### ISSUE TITLE
Hi sir ,what do you mean in this model 

### ISSUE THREAD

**Issue by Ahme1994** [coolsunxu/SSAE#1]
Hi sir ,what do you mean in this model SSAE
is it stacked sparce auto encoder ?

**Comment by coolsunxu** [comment]
Yes, after reading this paper, I found this model very interesting, so I realized it myself

**Comment by Ahme1994** [comment]
which paper do you mean ?

**Comment by coolsunxu** [comment]
A Multi-Modal States based Vehicle Descriptor and Dilated Convolutional Social Pooling for Vehicle Trajectory Prediction

**Comment by Ahme1994** [comment]
ok thank you a lot i will read it
